error: line 6: Type mismatch in assignment.
error: line 7: Type mismatch in assignment.
error: line 10: Type mismatch in assignment.
error: line 11: Type mismatch in assignment.
error: line 17: Type mismatch in assignment.
error: line 18: Type mismatch in assignment.
error: line 19: Type mismatch in assignment.
error: line 20: Type mismatch in assignment.
error: line 21: Type mismatch in assignment.
error: line 22: Type mismatch in assignment.
Compilation finished.

